---
title: "Seguimiento CNPV 2018"
author: CONAL
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    logo: Logo2.png
    #favlogo: Logo3.png
---

```{r paquetes, include = FALSE}
paquetes<-c("classInt","corrplot","flexdashboard","d3heatmap","DT","factoextra","FactoMineR","foreign","ggplot2","gridExtra","heatmaply","Hmisc","knitr","leaflet","maps","maptools","NbClust","openxlsx","pander","plotly","raster","RColorBrewer","reshape2","rgdal","rgeos","RPostgreSQL","scales","sf","spatstat","spdep","stringr","VIM","viridis")
# vector con los paquetes no instalados
instalaciones<-paquetes[!paquetes %in% installed.packages()]
# iteración para descargar los paquetes sin instalar
for(libs in instalaciones) install.packages(libs)
# carga de paquetes
sapply(paquetes,require,character=TRUE)
```

```{r infoalfa, include = FALSE}
#.rs.restartR()
gc()
rm(list = ls())

# alfanumerica
inicial<-read.csv(choose.files(default = "E:/R/CONAL/*.csv",caption = "TRANSMISION en csv"),header=TRUE,sep=";",stringsAsFactors=FALSE,encoding = "UTF-8")

grafica<-read.csv(choose.files(default = "E:/R/CONAL/*.csv",caption = "Fecha IET en csv"),header=TRUE,sep=";",stringsAsFactors=FALSE,encoding = "UTF-8")

# consolidado requerimientos
reqconal<-read.csv(choose.files(default = "E:/R/CONAL/*.csv",caption = "Consolidado requerimientos en csv"),header=TRUE,sep=";",stringsAsFactors=FALSE,encoding = "UTF-8")
str(reqconal)

# Coordenadas cabeceras
cab_coord<-read.table("C:/Geo/Cabeceras_Coords.txt", encoding = 'UTF-8',header=TRUE,sep="\t", dec=",",stringsAsFactors= FALSE)
cab_coord$DIVIPOLA<-str_sub(cab_coord$CODIGO_MUN,start=-5)
cab_coord$div_int<-as.numeric(cab_coord$DIVIPOLA)
cab_coord<-cab_coord[,c(6,7,4,5)]
str(cab_coord)

str(reqconal)
reqconal$DIVIPOLA<-ifelse(nchar(reqconal$Código.del.municipio) == 5,reqconal$Código.del.municipio, paste0(reqconal$Código.departamento,"001"))
reqconal$div_int<-as.numeric(reqconal$DIVIPOLA)
CONAL<-merge(reqconal,cab_coord,by="div_int")
CONALDF<-CONAL[,c(2:17,21:23)]
str(CONALDF)
CONALPto<-st_as_sf(CONAL, coords = c("Longitud", "Latitud"),crs = 4326, agr = "constant")
```

```{r infoalfa2, include = FALSE}
#Inicio
MunF2<-read.table("E:/R/CONAL/Municipios FaseII.csv",header=TRUE,sep=";",stringsAsFactors=FALSE,encoding = "UTF-8")
MunF3<-read.table("E:/R/CONAL/MUNICIPIOS FASEIII.csv",header=TRUE,sep=";",stringsAsFactors=FALSE,encoding = "UTF-8")
Inicio<-rbind(MunF2,MunF3)
table(Inicio$INICIO.OPERACIÓN)
```

```{r infogeo, include = FALSE}
# geografica
CAPITALES<-readOGR(dsn="C:/Geo",layer="Capitales",stringsAsFactors=FALSE,use_iconv=TRUE,encoding="UTF-8")

DPTOS_lin<-readOGR(dsn="C:/Geo",layer="Dept_lin",stringsAsFactors=FALSE,use_iconv=TRUE,encoding="UTF-8")
#str(DPTOS@data)

DPTOS<-readOGR(dsn="C:/Geo",layer="Departamentos",stringsAsFactors=FALSE,use_iconv=TRUE,encoding="UTF-8")
str(DPTOS@data)

MPIOS<-readOGR(dsn="C:/Geo",layer="Inicio",stringsAsFactors=FALSE,use_iconv=TRUE,encoding="UTF-8")
MPIOSIni<-MPIOS
MPIOST<-readOGR(dsn="C:/Geo",layer="Transmision",stringsAsFactors=FALSE,use_iconv=TRUE,encoding="UTF-8")
Trans<-MPIOST
```


```{r calculos, include = FALSE}
#Transmision
names(Trans@data)
Trans$div_int<-as.numeric(Trans$div_int)
Trans@data<-data.frame(as(Trans,"data.frame"),inicial[match(Trans@data[,"div_int"],inicial[,"ID_MPIO"]),])
Trans@data<-Trans@data[,c("OBJECTID_1","MUNICIPIO","ID_MPIO","div_int","COD_DEPART","DEPARTAMENTO","TRANSMITIDAS.A","NOTIFICADAS.B")]
Trans$Porcentaje <- ifelse((Trans$NOTIFICADAS.B == 0 | is.na(Trans$NOTIFICADAS.B)), 0,(Trans$TRANSMITIDAS.A / Trans$NOTIFICADAS.B ) * 100.00)
table(is.na(Trans$Porcentaje))
names(Trans@data)
writeOGR(obj=Trans, dsn="C:/Geo/Transmision_180526.shp",layer="Transmision_180526",driver="ESRI Shapefile",encoding="UTF-8",verbose=TRUE,overwrite_layer=TRUE)

#pal <- brewer.pal(4, "RdYlGn")
#pal<-c("#d9d9d9","#fd8d3c","#78c679","#f7fcb9")
#pal <- colorRampPalette(pal)


#Inicio
names(MPIOSIni@data)
MPIOSIni@data<-data.frame(as(MPIOSIni,"data.frame"),Inicio[match(MPIOSIni@data[,"div_int"],Inicio[,"COD.MUNICIPIO"]),])
MPIOSIni$INICIO<-ifelse((MPIOSIni$INICIO.OPERACIÓN == "NO") | is.na(MPIOSIni$INICIO.OPERACIÓN),"No","Si")
table(MPIOSIni$INICIO)
#writeOGR(obj=MPIOSIni[,c(1,6,13,17)], dsn="C:/Geo/Inicio_180528.shp",layer="Inicio_180528",driver="ESRI Shapefile",encoding="UTF-8",verbose=TRUE,overwrite_layer=TRUE)

```


Column {data-width=570}
-----------------------------------------------------------------------

### Distribución geográfica
```{r}
factpal <- colorFactor(c('#bababa','#70A800'), MPIOSIni$INICIO)
factpal2 <- c("#d9d9d9","#fd8d3c","#78c679","#f7fcb9")
palData <- classIntervals(Trans$Porcentaje, n=4, style="fixed",fixedBreaks=c(0.01,90,100,max(Trans@data$Porcentaje,na.rm = TRUE)))
Trans$colors <- findColours(palData, factpal2)


map <- leaflet(data= CONALPto) %>%

  ## Base group: default OpenStreetMap map tiles
  addProviderTiles("OpenStreetMap.Mapnik") %>%  setView(-74.0382679, 4.3489054, zoom = 11) %>%
  fitBounds(-78.201032746, 2.678125512, -71.6273344832, 11.552618168)%>%
  
  ## Overlay groups
  addMarkers(clusterOptions = markerClusterOptions())%>%
  addCircleMarkers(data=CAPITALES,radius = 2.2 ,stroke = FALSE, fillOpacity = 1, color = "#525252") %>%
  addPolylines(data = DPTOS_lin, stroke = TRUE, color = "#000000",opacity = 1, weight= 1) %>%
  addPolygons(data = MPIOSIni, stroke = FALSE, fillOpacity = 0.5, fillColor = ~factpal(INICIO)) %>%
  addPolygons(data = Trans, stroke = FALSE, fillOpacity = 0.8, fillColor = ~colors) %>%

  ## Layers control
  addLayersControl(overlayGroups = c("1","2","3","4","5"),options = layersControlOptions(collapsed = FALSE))%>%

  # Add legend
  addLegend(pal = factpal, values = MPIOSIni$INICIO, opacity = 0.5, title = 'Estado   inicio',position = "bottomleft")
  #addLegend(pal = factpal2, values = Trans$Porcentaje, opacity = 0.5, title = 'Transmisión',position = "bottomleft")
  
map


```

Column {data-width=430}
-----------------------------------------------------------------------

### Inicio de la operación

```{r, echo=FALSE}
str(reqconal)
torta1<-reqconal[,c(20,8:14)]

#pie<-data.frame(unlist(lapply(CONAL@data[, 5:11],sum)))
#pie$etiquetas<-c("Personal","Insumos","Transporte","Externalidades","Pre-Operativo","Operativo","TIC")
#colnames(pie)<-c("Conteo","Etiqueta")

#colors <- c('rgb(211,94,96)', 'rgb(128,133,133)', 'rgb(144,103,167)', 'rgb(171,104,87)', 'rgb(114,147,203)', 'rgb(77,175,74)', 'rgb(255,127,0)')




```


```{r}
#p <- plot_ly(pie, labels = ~Etiqueta, values = ~Conteo, type = 'pie',
#        #textposition = 'inside',
#        textinfo = 'label+percent',
#        insidetextfont = list(color = '#FFFFFF'),
#        hoverinfo = 'text',
#        text = ~paste(Conteo, 'solicitudes'),
#        marker = list(colors = colors,
                      #line = list(color = '#FFFFFF', width = 1)),
#        showlegend = TRUE) %>%
#  layout(title = 'Proporción de requerimientos de acuerdo al tipo',
#         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
#         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

#p
```

### Transmisión de la información

```{r}
grafica$fecha<-as.Date(grafica$Fecha, "%d/%m/%y")
grafica$perc<-grafica$Transmitidas/grafica$Notificadas*100
p <- plot_ly(grafica, x = ~ fecha, y = ~ Transmitidas, type = 'scatter', mode = 'lines+markers', name = 'Transmitidas') %>%
  add_trace(y = ~Notificadas, name = 'Notificadas', mode = 'lines+markers') %>% layout(legend = list(x = 0.02, y = .95))
p
```